### ISSUE TITLE
Add boxes for entering custom number of questions.

### ISSUE THREAD

**Issue by jdoyle65** [jdoyle65/rudi_gui#4]

**Comment by jdoyle65** [comment]
Done

**Comment by eugenecormier** [comment]
Hey Justin, can the number boxes default to rudi's defaults, they all default to 1 which is probably not what people want

**Comment by eugenecormier** [comment]
great work btw!!!

**Comment by jdoyle65** [comment]
Absolutely! I'll add it as an enhacement.
