### ISSUE TITLE
Unable to extract generated archive

### ISSUE THREAD

**Issue by HisaoNakai** [jdoyle65/rudi_gui#6]
Output from unzip -

unzip rudi-test.zip                                                                                                                         
Archive:  rudi-test.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of rudi-test.zip or
        rudi-test.zip.zip, and cannot find rudi-test.zip.ZIP, period.

When attempting to open with Ark -
Loading the archive <path> failed with the following error: Could not open the archive <path>, libarchive cannot handle it.

**Comment by jdoyle65** [comment]
No longer using zip files.
